language: node_js
node_js:
- '10'
install:
- npm install
script:
- npm run build
git:
  depth: 10
deploy:
  provider: releases
  api_key:
    secure: pJC4Ll1Z9VE4mH8OdYhLczY6dRlbJT7WdLMTui05i/RxkfEc4Hezh4PP1v5iPTjW0nmZzstCxgc5uLKJc5gsVja2HBRkO8mPWjE82Bs2mmaZUoowSHhZLFDgyqFmUkbZ0E2HKwEL3Dy1qdvyaM5Jx129Fk+QoZoYkRvL2vysim672api4CthIFH4KMdxLeXK6zNc5kqF1c1CCLAE8eNqC7ARe4Z4Xll2zMLHZSjaA13tgFlAXvPZebYtziyie1DalyAcHD2wDzSVBkplmHAaGIIXUxKEpDqXhO6/ZDfgsp13XqixjdjNJONx3DjNCQqsSnW76Qi6AJQ5K8+1MXJe6sfPpLMMPv//EeNkxMVidTA5Oy2FtOLGP7g31IScTBgSOAHRCuUol4GkfzIaPA+A/X/DRO1K2NXKRx1VAG7lPnF8gVZVqqcEI+iqVynSYGKGaoZ8xqBUIfaFwkGhdDowSz3B9f+HH1pJUQb3jKSHOHHevnNDpF5htNVn8v7EBkLthEXAOy83aP4PMbvLV80knzlA34NOu/JrwAvTVaOpWP0CMK0wG3W2xjh0nwaqdR/R2Usr3c1pb64HcbFEzjHYmlmF/ZUiEn2lnhznnv1JRSIcBLElFc531hdk/xR5pyBQH0sWGfyDz9Q+H7BJtVCDal5bsRElmjZoUlQlwJJT7hY=
  file_glob: true
  file: dist/**/*
  on:
    repo: hyubs/pipeline-test
    branch: master
  skip_cleanup: true
  tag: next
